### ISSUE TITLE
Project name definition

### ISSUE THREAD

**Issue by karlitoz007** [ViniciusSouza/TinderBot#3]
Let select a name for our project!

My suggestions:
1. [AlphaBot / Alphy](https://simple.wikipedia.org/wiki/Alpha_male)
2. [CasanoBot / Casanov](https://en.wikipedia.org/wiki/Giacomo_Casanova)
3. [HitchBot / Hitchy / Alex](https://en.wikipedia.org/wiki/Hitch_%28film%29)
4. [GentleBot](https://en.wikipedia.org/wiki/Gentleman)

What do you think?

**Comment by allantargino** [comment]
HitchBot is amazing hahahaha

**Comment by MizhaVL** [comment]
HitchBot +1

**Comment by ViniciusSouza** [comment]
So HitchBot it is
